guitar:
  fretboard-settings:
    number-of-frets: 21
    number-of-strings: 6
    tuning:
      - note: E
        octave: 1
      - note: B
        octave: 0
      - note: G
        octave: 0
      - note: D
        octave: 0
      - note: A
        octave: -1
      - note: E
        octave: -1

search:
  search-options:
    use-thumb-finger: false
    use-open-strings: false
  weight-options:
    every-pick: 0.1
    fret-distance: 1
    string-distance: 1
    finger-distance: 1
    finger-distance-from-index: 0.1